import {
  borderRadius,
  colors,
  fontSize,
  spacing,
  typography,
} from "@/theme/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.gray[100],
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: spacing.xl,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray[100],
    backgroundColor: colors.purple[500],
  },
  headerButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: {
    fontSize: fontSize.xl,
    fontFamily: typography.bold,
    color: colors.white,
  },
  keyboardView: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.xl,
  },
  section: {
    marginBottom: spacing.xl,
  },
  label: {
    fontSize: fontSize.md,
    fontFamily: typography.semibold,
    color: colors.gray[800],
    marginBottom: spacing.md,
  },
  dataSeletor: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    paddingHorizontal: spacing.md,
    marginTop: spacing.sm,
  },
  dataButton: {
    padding: spacing.sm,
  },
  dataDisplay: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  dataTexto: {
    fontSize: fontSize.lg,
    fontFamily: typography.semibold,
    color: colors.gray[800],
  },
  valorContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
  },
  cifrao: {
    fontSize: fontSize.xxxl,
    fontFamily: typography.bold,
    color: colors.gray[600],
    marginRight: spacing.sm,
  },
  valorInput: {
    flex: 1,
    fontSize: fontSize.xxxl,
    fontFamily: typography.bold,
    color: colors.gray[800],
  },
  categoriasContainer: {
    gap: spacing.md,
  },
  categoriaButton: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    borderWidth: 2,
    borderColor: colors.gray[100],
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.xl,
    minWidth: 100,
  },
  categoriaTexto: {
    fontSize: fontSize.sm,
    fontFamily: typography.semibold,
    color: colors.gray[600],
    marginTop: spacing.xs,
  },
  categoriaTextoActive: {
    color: colors.white,
  },
  descricaoInput: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    fontSize: fontSize.md,
    color: colors.gray[800],
    minHeight: 50,
  },
  recorrenciaButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    gap: spacing.md,
  },
  recorrenciaTextoContainer: {
    flex: 1,
  },
  recorrenciaLabel: {
    fontSize: fontSize.md,
    fontFamily: typography.semibold,
    color: colors.gray[800],
  },
  recorrenciaDescricao: {
    fontSize: fontSize.sm,
    color: colors.gray[600],
    marginTop: 2,
  },
  tagsContainer: {
    gap: spacing.sm,
  },
  tagButton: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    backgroundColor: colors.white,
    borderRadius: borderRadius.round,
    borderWidth: 1,
    borderColor: colors.gray[100],
  },
  tagButtonActive: {
    backgroundColor: colors.purple[500],
    borderColor: colors.purple[500],
  },
  tagTexto: {
    fontSize: fontSize.md,
    color: colors.gray[600],
    fontFamily: typography.medium,
  },
  tagTextoActive: {
    color: colors.white,
  },
  salvarButton: {
    backgroundColor: colors.purple[500],
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    alignItems: "center",
    marginTop: spacing.md,
  },
  salvarButtonDisabled: {
    opacity: 0.6,
  },
  salvarTexto: {
    fontSize: fontSize.lg,
    fontFamily: typography.bold,
    color: colors.white,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: colors.white,
    borderTopLeftRadius: borderRadius.xl,
    borderTopRightRadius: borderRadius.xl,
    maxHeight: "75%",
    paddingBottom: spacing.xxl,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: spacing.xl,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray[100],
  },
  modalTitulo: {
    fontSize: fontSize.xl,
    fontFamily: typography.bold,
    color: colors.gray[800],
  },
  recorrenciaOption: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray[100],
  },
  recorrenciaOptionActive: {
    backgroundColor: colors.gray[200],
  },
  recorrenciaOptionLabel: {
    fontSize: fontSize.md,
    fontFamily: typography.semibold,
    color: colors.gray[800],
  },
  recorrenciaOptionDescricao: {
    fontSize: fontSize.sm,
    fontFamily: typography.regular,
    color: colors.gray[600],
    marginTop: 2,
  },
  modalExclusaoContent: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.xl,
    padding: spacing.xxl,
    marginHorizontal: spacing.xl,
    maxWidth: 400,
    alignSelf: "center",
  },
  modalExclusaoHeader: {
    alignItems: "center",
    marginBottom: spacing.xxl,
  },
  modalExclusaoTitulo: {
    fontSize: fontSize.xl,
    fontFamily: typography.bold,
    color: colors.gray[800],
    marginTop: spacing.lg,
    textAlign: "center",
  },
  modalExclusaoSubtitulo: {
    fontSize: fontSize.md,
    fontFamily: typography.regular,
    color: colors.gray[600],
    marginTop: spacing.sm,
    textAlign: "center",
  },
  opcaoExclusaoButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.gray[200],
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    marginBottom: spacing.md,
    borderWidth: 2,
    borderColor: "transparent",
  },
  opcaoExclusaoButtonDanger: {
    backgroundColor: colors.red[200],
  },
  opcaoExclusaoTexto: {
    flex: 1,
    marginLeft: spacing.md,
  },
  opcaoExclusaoTitulo: {
    fontSize: fontSize.md,
    fontFamily: typography.semibold,
    color: colors.gray[800],
    marginBottom: 4,
  },
  opcaoExclusaoDescricao: {
    fontSize: fontSize.sm,
    fontFamily: typography.regular,
    color: colors.gray[600],
  },
  cancelarExclusaoButton: {
    padding: spacing.lg,
    alignItems: "center",
    marginTop: spacing.md,
  },
  cancelarExclusaoTexto: {
    fontSize: fontSize.md,
    fontFamily: typography.semibold,
    color: colors.gray[600],
  },
});
