import {
  borderRadius,
  colors,
  fontSize,
  spacing,
  typography,
} from "@/theme/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.gray[50],
  },
  keyboardView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: spacing.xxl,
    paddingTop: spacing.xxl * 2,
    paddingBottom: spacing.xxl,
  },
  header: {
    alignItems: "center",
    marginBottom: spacing.xxl * 2,
  },
  iconContainer: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: colors.purple[100],
    justifyContent: "center",
    alignItems: "center",
    marginBottom: spacing.xl,
  },
  title: {
    fontSize: fontSize.xxxl,
    fontFamily: typography.bold,
    color: colors.gray[800],
    marginBottom: spacing.sm,
    textAlign: "center",
  },
  subtitle: {
    fontSize: fontSize.md,
    fontFamily: typography.regular,
    color: colors.gray[600],
    textAlign: "center",
  },
  form: {
    flex: 1,
  },
  section: {
    marginBottom: spacing.xxl,
  },
  label: {
    fontSize: fontSize.lg,
    fontFamily: typography.semibold,
    color: colors.gray[800],
    marginBottom: spacing.xs,
  },
  helper: {
    fontSize: fontSize.sm,
    fontFamily: typography.regular,
    color: colors.gray[600],
    marginBottom: spacing.md,
  },
  valorContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    borderWidth: 2,
    borderColor: colors.purple[500],
  },
  cifrao: {
    fontSize: fontSize.xxxl,
    fontFamily: typography.bold,
    color: colors.gray[600],
    marginRight: spacing.sm,
  },
  valorInput: {
    flex: 1,
    fontSize: fontSize.xxxl,
    fontFamily: typography.bold,
    color: colors.gray[800],
  },
  dataSeletor: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    borderWidth: 2,
    borderColor: colors.purple[500],
  },
  dataButton: {
    padding: spacing.sm,
  },
  dataDisplay: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  dataTexto: {
    fontSize: fontSize.lg,
    fontFamily: typography.semibold,
    color: colors.gray[800],
  },
  infoBox: {
    flexDirection: "row",
    backgroundColor: colors.blue[100],
    padding: spacing.lg,
    borderRadius: borderRadius.lg,
    gap: spacing.md,
    marginTop: spacing.xl,
  },
  infoText: {
    flex: 1,
    fontSize: fontSize.sm,
    fontFamily: typography.regular,
    color: colors.blue[900],
    lineHeight: 20,
  },
  input: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    fontSize: fontSize.lg,
    fontFamily: typography.regular,
    color: colors.gray[800],
    borderWidth: 1,
    borderColor: colors.purple[500],
  },

  // inputModal: {
  //   backgroundColor: colors.gray[50],
  //   borderRadius: borderRadius.lg,
  //   padding: spacing.lg,
  //   fontSize: fontSize.lg,
  //   fontFamily: typography.regular,
  //   color: colors.gray[800],
  //   borderWidth: 1,
  //   borderColor: colors.gray[200],
  // },

  footer: {
    flexDirection: "row",
    gap: spacing.md,
    padding: spacing.xl,
    borderTopWidth: 1,
    borderTopColor: colors.gray[200],
  },
  salvarButton: {
    backgroundColor: colors.purple[500],
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    alignItems: "center",
  },
  salvarButtonDisabled: {
    opacity: 0.6,
  },
  salvarTexto: {
    fontSize: fontSize.lg,
    fontFamily: typography.bold,
    color: colors.white,
  },
  progressContainer: {
    paddingHorizontal: spacing.xxl,
    paddingVertical: spacing.lg,
  },
  progressBar: {
    height: 4,
    backgroundColor: colors.gray[200],
    borderRadius: borderRadius.sm,
    overflow: "hidden",
    marginBottom: spacing.sm,
  },
  progressFill: {
    height: "100%",
    backgroundColor: colors.purple[500],
  },
  progressText: {
    fontSize: fontSize.sm,
    fontFamily: typography.regular,
    color: colors.gray[600],
    textAlign: "center",
  },
  diasSeletor: {
    flexDirection: "row",
    gap: spacing.md,
  },
  diaButton: {
    flex: 1,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: borderRadius.md,
    borderWidth: 2,
    borderColor: colors.gray[300],
    backgroundColor: colors.white,
    alignItems: "center",
  },
  diaButtonActive: {
    borderColor: colors.purple[500],
    backgroundColor: colors.purple[500] + "10",
  },
  diaButtonText: {
    fontSize: fontSize.md,
    fontFamily: typography.semibold,
    color: colors.gray[600],
  },
  diaButtonTextActive: {
    color: colors.purple[500],
  },
  listHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.lg,
  },
  addButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.purple[500],
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
    borderRadius: borderRadius.md,
    gap: 6,
  },
  addButtonText: {
    color: colors.white,
    fontSize: fontSize.md,
    fontFamily: typography.semibold,
  },
  emptyState: {
    alignItems: "center",
    paddingVertical: 48,
  },
  emptyText: {
    fontSize: fontSize.lg,
    fontFamily: typography.semibold,
    color: colors.gray[600],
    marginTop: spacing.lg,
  },
  emptySubtext: {
    fontSize: fontSize.md,
    fontFamily: typography.regular,
    color: colors.gray[400],
    marginTop: spacing.sm,
  },
  resumo: {
    backgroundColor: colors.purple[500] + "10",
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    marginTop: spacing.lg,
  },
  resumoLinha: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  resumoLabel: {
    fontSize: fontSize.md,
    fontFamily: typography.regular,
    color: colors.gray[600],
  },
  resumoValor: {
    fontSize: fontSize.lg,
    fontFamily: typography.semibold,
    color: colors.gray[800],
  },
  resumoLabelDestaque: {
    fontSize: fontSize.lg,
    fontFamily: typography.bold,
    color: colors.purple[700],
  },
  resumoValorDestaque: {
    fontSize: fontSize.xl,
    fontFamily: typography.bold,
    color: colors.purple[700],
  },
  divider: {
    height: 1,
    backgroundColor: colors.gray[200],
    marginVertical: spacing.md,
  },
  // Botão Voltar
  voltarButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.xxl,
    borderRadius: borderRadius.lg,
    borderWidth: 2,
    borderColor: colors.purple[500],
    backgroundColor: colors.white,
    gap: spacing.sm,
  },
  voltarTexto: {
    fontSize: fontSize.lg,
    fontFamily: typography.semibold,
    color: colors.purple[500],
  },

  // Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: colors.white,
    borderTopLeftRadius: borderRadius.xl,
    borderTopRightRadius: borderRadius.xl,
    paddingBottom: 32,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: spacing.xxl,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray[100],
  },
  modalTitulo: {
    fontSize: fontSize.xl,
    fontFamily: typography.bold,
    color: colors.gray[900],
  },
  modalBody: {
    padding: spacing.xxl,
  },
  modalButton: {
    backgroundColor: colors.purple[500],
    paddingVertical: spacing.lg,
    borderRadius: borderRadius.lg,
    alignItems: "center",
    marginTop: spacing.xxl,
  },
  modalButtonText: {
    color: colors.white,
    fontSize: fontSize.lg,
    fontFamily: typography.semibold,
  },
});
